
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from gpiozero import LED, PMWLED


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Samue\OneDrive - Universidad del Norte\Noveno Semestre\PF\Tkinter-Designer-Master\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("543x322")
window.configure(bg = "#0E174B")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 322,
    width = 543,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    543.0,
    61.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    76.0,
    17.0,
    anchor="nw",
    text="Control de irradiancia",
    fill="#000000",
    font=("LeagueSpartan Bold", 24 * -1)
)

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=46.0,
    y=98.0,
    width=130.0,
    height=50.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=46.0,
    y=149.0,
    width=130.0,
    height=50.0
)

canvas.create_rectangle(
    442.0,
    8.0,
    489.0,
    52.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
