
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

from tkinter import *
# Explicit imports to satisfy Flake8
#import RPi.GPIO as GPIO
from gpiozero import LED,PWMLED
#funciones de apagr y prender
#hola

led=PWMLED(18)
def intensidad(event):
    event=slider1.get()
    led.value=event*0.01
def apagar():
    button_1["state"]=NORMAL #habilita boton encender
    button_2["state"]=DISABLED # desabilita el boton apagar
    slider1.set(0)
    intensidad
    slider1["state"]=DISABLED #desabilita slider


def encender(): 
    button_2["state"]=NORMAL #habiliad boton apagar
    button_1["state"]=DISABLED #desabilita boton apagar
    slider1["state"]=NORMAL # habilita slider
    slider1.set(100)
    intensidad
    
#GUI
OUTPUT_PATH = Path(_file_).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/pi/Descargas/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x500")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 500,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    2.842170943040401e-14,
    800.0,
    50.00000000000003,
    fill="#2645B0",
    outline="")

canvas.create_text(
    27.999999999999943,
    10.999999999999972,
    anchor="nw",
    text="Leds usando Tkinter",
    fill="#FFFFFF",
    font=("MontserratRoman Regular", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=encender,
    relief="flat"
)
button_1.place(
    x=17.999999999999943,
    y=175.99999999999997,
    width=122.0,
    height=29.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=apagar,
    relief="flat"
)
button_2.place(
    x=172.99999999999994,
    y=175.99999999999997,
    width=122.0,
    height=29.0
)
button_2["state"]=DISABLED

#slider led 1
slider1 = Scale(window, from_=0,to=100, orient=HORIZONTAL,relief=FLAT,
                widt=5,length=260,background="#22A6F2",
                command=intensidad)
slider1.place(x=21 , y=220)
slider1["state"]=DISABLED #desabilitar cuando carga
canvas.create_text(
    106.99999999999994,
    68.99999999999997,
    anchor="nw",
    text="LED 1",
    fill="#000000",
    font=("MontserratRoman Regular", 32 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    642.0,
    131.99999999999997,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    149.99999999999994,
    138.99999999999997,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()